imports:
- path: Environment_MVP.py
- path: instance_MVP.py
  
resources:
 - name: transformation-engine
   type: Evironment_MVP.py
   properties:
     zone: us-central1-a
     template: https://www.googleapis.com/compute/v1/projects/
     machineType: n1-standard-2
     namePrefix: transformation-engine
 - name: app
   type: instance_MVP.py
   properties:
    zone: us-central1-a
    image: https://www.googleapis.com/compute/v1/projects/
    machineType: n1-standard-4
    namePrefix: app
